name: test and benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    
    # 创建一个测试数据库
    services:
      postgresql:
        image: 'bitnami/postgresql:latest'
        env:
          POSTGRESQL_USERNAME: testuser
          POSTGRESQL_PASSWORD: justfortest
          POSTGRESQL_DATABASE: testdatabase
          POSTGRESQL_POSTGRES_PASSWORD: password
        ports:
          - '5432:5432'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24

    - name: Install dependencies
      run: go mod tidy

    # 找出带有 _test.go 后缀的文件的目录,然后运行 go test
    - name: Run tests
      run: |
        find . -name "*_test.go" | xargs -n 1 dirname | sort -u | xargs go test -v | tee test-results.txt

    - name: Run benchmark
      run: |
        find . -name "*_test.go" | xargs -n 1 dirname | sort -u | xargs go test -bench=. -v -run="^(Benchmark)" | tee benchmark-results.txt

    - name: Save test results as summary
      if: success() || failure()
      run: |
        echo "### Test Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat test-results.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY

    - name: Save benchmark results as summary
      if: success() || failure()
      run: |
        echo "### Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat benchmark-results.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY